
export const icelandic_texts: Record<string, string> = {
    welcome_WELCOME: "Velkomin(n)",
    welcome_thankInterest: 'Takk fyrir áhugann',
    welcome_studyBasics: 'Þessi rannsókn kannar hvernig vel töflureikna forrit geta verið stjórnað með talmáta eða teikningum.',
    welcome_furtherInformationButton: 'Ýttu á takkann fyrir neðan til að fá frekar upplýsingar.',
    welcome_GERMAN: "Skipta yfir á þýsku",
    welcome_ENGLISH: "Skipta yfir á ensku",
    welcome_goOn: "Halda áfram að samþykktarformi",
    welcome_nextPage: "Næsta síða",
    //     consent form:
    welcome_intro: "Vinsamlegast lestu skjalið varlega og kvittaðu undir að þú býður þig fram í þátttöku rannsóknarinnar. Þú getur beðið um afrit af skjalinu.",
    welcome_purposeHeader: "Tilgangur rannsóknarinnar",
    welcome_purpose: "Þessi rannsókn reynir að skilja hvernig notendur notfæra sér töflureikna (e. spreadsheets) með því að teikna á snertifleti og framkvæma skipanir á talmáta, sem valkvæman kost í stað hefðbundnari tólum eins og mús og lyklaborð. Niðurstöður rannsóknarinnar gæti lagt sitt af mörkum til hönnunar og þróun á því hvernig við notum töflureikni forrit.",
    welcome_implementationHeader: "Framkvæmd tilraunarinnar",
    welcome_implementation: "Þú færð spjaldtölvu með snertifleti og stafrænan penna. Rannsakandinn mun sýna þér nokkur pör af skjáskotum sem sýna fyrir og eftir myndir af tilætluðum breytingum miðað við einhverja aðgerð (e. operation). Þegar þú hefur greint hver sú aðgerð er máttu nota stafræna pennan og/eða segja skipun (e. voice command) til þess að framkvæma aðgerðina. Rannsakandinn mun fyrst sýna þér tvö dæmi og útskýra hvernig skal framkvæma verkefnin. Þú verður beðin(n) um að halda áfram á eigin spýtur í framhaldi. Eftir hverja fyrirspurn geturðu gefið endurgjöf um hversu erfitt tiltekna verkefnið er. Framkvæmd rannsóknarinnar tekur um það bil 30 mínutur. Eftir rannsóknina mun rannsakandinn spyrja lýðfræðilegar spurningar (e. demographic questions) um þig og þína reynslu.",
    welcome_collectionHeader: "Gagnasöfnun og trúnaðarmál",
    welcome_collectionFirstSentence: "Í þessari rannsókn munum við safna eftirfarandi gögnum:",
    welcome_collectionItem1: "Upptöku af skjá og stafrænu bleki frá pennanum yfir á skjáinn.",
    welcome_collectionItem2: "Upptöku af röddinni þinni, þar á meðal allar skipanir, athugasemdir, eða samtöl sem eiga sér stað á meðan rannsókninni stendur yfir.",
    welcome_collectionItem3: "Endurgjöf og lýðfræðilegar upplýsingar",
    welcome_collectionBlock1: "Upptakan af skjánum og stafræna blekinu verður notað til þess að greina hvernig þátttakendur notfæra sér stafrænan penna og talmáta til þess að tjá skipanir innan töflureikna. Endurgjöfin verður notuð til þess að veita samhengi um notendaupplifun þátttakenda. Lýðfræðilegugögnin verða notuð til að greina einkenni þátttakendahópsins til þess að forðast úrtaksskekkju.",
    welcome_collectiobBlock2: "Öll gögn í rannsókninni eru nafnlaus (þ.a.s., þeim verður úthlutað númer í stað nafns þíns), til þess að gögnin séu ekki rekjanleg til þín. Hluti af nafnlausu gögnunum (umritun án raddar þinnar) kann að vera birt í einstaklingsbundnu eða samanlögðu formi. Öllum hljóðgögnum verða eytt í síðasta lagi fyrir 1. febrúar 2028.",
    welcome_RefusalHeader: "Neitun eða afturköllun",
    welcome_Refusal: "Þú hefur rétt til þess að neita þáttekt í rannsókninni eða afturkalla samþykki þitt hvenær sem er án þess að gefa ástæðu og án þess að hafa í för með sér neikvæðar afleiðingar. Gögn sem voru söfnuð fyrir afturköllun er hægt að nota með þínu samþykki. Eftir að rannsókinni lýkur er ekki hægt að banna notkun gagna eða krefjast að þeim verði eytt.",
    welcome_IncentiveHeader: "Hvati",
    welcome_Incentive: "Það eru engin verðlaun, greiðslur eða aðrir hvatar til þátttöku.",
    welcome_contactHeader: "Tengiliðar",
    welcome_contact_firstSentence: "Aðalrannsakendur í þessu verkefni er:",
    welcome_contact1: "Dr. Matthias Book, prófessor hjá tölvunarfræðideild Háskóla Íslands (book@hi.is),",
    welcome_contact2: "Dr. Marc Hesenius, nýdóktor hjá University of Hildesheim, Þýskalandi (hesenius@uni-hildesheim.de),",
    welcome_contact3: "og Marvin Bachert, doktorsnemi hjá University Duisburg-Essen, Þýskalandi (marvin.bachert@uni-due.de).",
    welcome_contactFunding: "Þessi rannsókn er studd af Rannsóknarmiðstöð Íslands (styrkur nr. 2410725).",
    welcome_contactQuestions: "Ef þú hefur einhverjar spurningar um rannsóknina eða þátttöku þína, vinsamlegast ekki hika við að spyrja rannsakandann hvenær sem er.",

    task_next: "Næsta Síða",
    task_reset: "Endurræsa",
    task_previous: "Fyrri Síða  ",
    task_skip: "Sleppa",
    task_questionnaire: "Spurningalisti",
    task_questionnaire_question1: "Hversu auðveld var þessi atburðarás?",
    task_questionnaire_veryEasy: "Mjög auðveld",
    task_questionnaire_easy: "Auðveld",
    task_questionnaire_neutral: "Hlutlaus",
    task_questionnaire_difficult: "Erfið",
    task_questionnaire_veryDifficult: "Mjög erfið",

    sketch_before: "fyrir",
    sketch_after: "eftir",
    sketch_hint: "Vísbending",

    demographics_header: "Lýðfræðilegar upplýsingar",
    demographics_previous: "Fyrri Síða",
    demographics_next: "Ljúka Rannsókn",
    demographics_gender: "Kyn",
    demographics_female: "Kvenkyns",
    demographics_male: "Karlkyns",
    demographics_nonbinary: "non-binary",
    demographics_noanswer: "Vil helst ekki segja",
    demographics_age: "Aldur",
    demographics_hand: "Hvaða hönd notar þú til þess að skrifa?",
    demographics_left: "Vinstri",
    demographics_right: "Hægri",
    demographics_nativeLanguage: "Hvert er móðurmál þitt?",
    demographics_placeholder: "no answer",
    demographics_experienceVoice: "Hefur þú reynslu af því að nota rödd til að hafa samskipti með tæknibúnaði?",
    demographics_none: "Enga",
    demographics_little: "Smá",
    demographics_lot: "Mikla",
    demographics_experienceTablet: "Hefur þú reynslu af spjaldtölvum?",
    demographics_experiencePen: "Hefur þú reynslu af því að nota stafræna penna?",
    demographics_experienceSpreadsheets: "Hefur þú reynslu af töflureiknum (e. spreadsheet) forritum?",

    acknowledgement_header: "Þakkir",
    acknowledgement_newStart: "Endurræsa rannsóknina",
    acknowledgement_thankYou: "Þakka þér fyrir þátttökuna!",
    acknowledgement_weThank: "Við viljum þakka þér innilega fyrir þáttöku þína í rannsókninni. Þáttakan þín hjálpar okkur að öðlast mikilvæg innsýni.",
    acknowledgement_yourData: "Gögnum þínum hefur verið safnað vandlega og verður trúnaðarmál. Við munum aðeins nota upplýsingarnar í vísindalegum tilgangi og verður ekki deilt með neinum þriðja aðila.",
    acknowledgement_questions: "Ef þú hefur frekari spurningar eða vilt vita meira um rannsóknina, vinsamlegast hafðu samband við okkur. Álit þitt og endurgjöf eru okkur mikilvæg.",
    acknowledgement_thanksAgain: "Aftur þakkir fyrir þátttökuna!",
    acknowledgement_team: "Rannsóknarteymi",

    task13: "Dálkur C",
    hintG: "Reikningur, t.d. K7 = SUM(E7:J7)/6",
    hint8: "sum",
    hint16: "Hvernig hafa nöfnin verið endurröðuð?",
    hint17: "Reikningur: Samtals klukkutímar/mánuður, t.d. G13 = SUM(G7:G11)",
    hint18: "Reikningur: brúttó tímakaup",
    hint19: "Skilyrt snið",
    hint20: "Reikningur: samtals laun Smiths, L7 = C7*SUM(E7:J7)",
    senior: "Reyndur",
    junior: "Starfsnema",
    architect: "hönnuður",
    developer: "forritari",
    design: "framendahönnuður",
    // abbreviations for months:
    jan: "jan",
    feb: "feb",
    mar: "mar",
    apr: "apr",
    may: "may",
    jun: "jun"

};
